run:
  out_dir: "./data_runs/pinch_bennett_Bz1"
  output_every: 50
  diag_every: 10

grid:
  Nr: 192          # suficiente resolución para probar
  Nz: 192
  Ng: 2
  Rmax: 0.01       # 1 cm
  Zmax: 0.10       # 10 cm

time:
  t_end: 2.0e-06   # prueba corta: 2 microseg
  cfl: 0.10        # más conservador
  dt_max: 2.0e-09  # techo más bajo
  vmax_guard: 50.0 # limita la onda para dt

phys:
  gamma: 5.0/3.0
  Bz0: 3.0         # MÁS Bz estabiliza (kink) el arranque
  eta_ct: 1.0e-02  # más difusión en induction/CT para suavizar ∇·B
  limiter: "minmod"
  bc_z: "periodic"
  problem: "pinch_bennett"

modes:
  enable: false
  m: 0
  k: 2.0*np.pi/0.1
  eps: 0.00
  r0_frac: 0.35
  seed_vr: true
  seed_bth: false

