out_dir: "./data_runs/pinch_axialBennett_Bz3_fix"

grid:
  Nr: 256
  Nz: 256
  Rmax: 0.01
  Zmax: 0.04
  Ng: 2

phys:
  Bz0: 3.0

mhd2d:
  problem: "pinch_bennett"
  gamma: 1.4
  cfl: 0.25          # <- más conservador
  dt_max: 3.0e-10    # <- evita saltos cuando sube Bth
  t_end: 2.0e-6
  limiter: "minmod"
  bc_z: "periodic"
  eta_ct: 1.0e-3     # <- pequeña resistividad numérica
  vmax_guard: 0.0
  diag_every: 100

modes:
  enable: false
  eps: 0.0
  k: 62.8318530718
  m: 0
  r0_frac: 0.35
  seed_vr: false
  seed_bth: false

output_every: 100

